# require 'azure_env_secrets'
# require 'active_support/core_ext/string'
# require 'sidekiq_alive'
# require 'sidekiq'
# require_relative 'config/initializers/azure_env_secrets'
# require_relative 'config/initializers/sidekiq'
# require_relative 'app/workers/et_exporter/export_claim_worker'
